/*
===============================================================================
 AdventureWorks Sales Analytics
 03 - CREATE ACTION MONITORING SNAPSHOT PROCEDURE
===============================================================================

Purpose:
- Refresh the staging table from the CSV generated by the Commercial Actions
  workflow.
- Convert formatted text values (currency, percentages and separators) into
  numeric fields suitable for analysis.
- Replace the previous monitoring baseline with a new snapshot dated at the
  execution day.
- Store the Country x Subcategory baseline used by the Action Monitoring page
  to measure subsequent recovery against the initial gap.

Workflow:
  1) Clear the CSV staging table.
  2) Import the latest CSV file.
  3) Clear the previous snapshot.
  4) Clean and convert imported values.
  5) Insert the new monitoring snapshot.
  6) Return the stored snapshot as an execution check.

Important:
- The SQL Server service account must have read access to C:\SQL_IMPORT\data.csv.
- The staging and snapshot tables must already exist in the project schema.
- The procedure intentionally keeps one active snapshot at a time because the
  snapshot table is truncated before each new monitoring cycle.
===============================================================================
*/

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [project].[sp_Create_ActionMonitoringSnapshot]
AS
BEGIN

    SET NOCOUNT ON;

    DECLARE @SnapshotDate date = CAST(GETDATE() AS date);

    BEGIN TRY

        --------------------------------------------------
        -- 1. PULIZIA IMPORT
        --------------------------------------------------
        TRUNCATE TABLE Project.ActionMonitoring_Import;


        --------------------------------------------------
        -- 2. IMPORT CSV
        --------------------------------------------------
        BULK INSERT Project.ActionMonitoring_Import
        FROM 'C:\SQL_IMPORT\data.csv'
        WITH
        (
            FORMAT = 'CSV',
            FIRSTROW = 2,
            FIELDQUOTE = '"',
            CODEPAGE = '65001',
            ROWTERMINATOR = '0x0a'
        );


        --------------------------------------------------
        -- 3. PULIZIA SNAPSHOT PRECEDENTE
        --------------------------------------------------
        TRUNCATE TABLE Project.ActionMonitoringSnapshot;


        --------------------------------------------------
        -- 4. CONVERSIONE DATI CSV
        --------------------------------------------------
        ;WITH ImportPulito AS
        (
            SELECT

                Subcategory,
                Country,
                PriorityType,


                ------------------------------------------
                -- CURRENT REVENUES
                -- € 185,333.00 -> 185333.00
                ------------------------------------------
                TRY_CONVERT(
                    decimal(18,2),
                    REPLACE(
                        REPLACE(
                            REPLACE(
                                REPLACE(
                                    CurrentRevenues,
                                    '€',
                                    ''
                                ),
                                ',',
                                ''
                            ),
                            '"',
                            ''
                        ),
                        ' ',
                        ''
                    )
                ) AS SnapshotRevenue,


                ------------------------------------------
                -- % CURRENT / GOAL
                -- -57.74% -> -57.74
                ------------------------------------------
                TRY_CONVERT(
                    decimal(18,4),
                    REPLACE(
                        REPLACE(
                            REPLACE(
                                PercCurrentGoal,
                                '%',
                                ''
                            ),
                            '"',
                            ''
                        ),
                        ' ',
                        ''
                    )
                ) AS PercCurrentSnapshotGoal,


                ------------------------------------------
                -- DELTA MONETARIO
                -- -€ 253,268.84 -> -253268.84
                ------------------------------------------
                TRY_CONVERT(
                    decimal(18,2),
                    REPLACE(
                        REPLACE(
                            REPLACE(
                                REPLACE(
                                    DeltaCurrentGoal,
                                    '€',
                                    ''
                                ),
                                ',',
                                ''
                            ),
                            '"',
                            ''
                        ),
                        ' ',
                        ''
                    )
                ) AS DeltaCurrentSnapshotGoal,

				 ------------------------------------------
            -- CURRENT SNAPSHOT GOAL
            --
            -- Revenue / (1 + %Delta)
            --
            -- esempio:
            -- 185333 / (1 - 0.5774)
            -- = 438554.19
                ------------------------------------------
                TRY_CONVERT(
                    decimal(18,2),
                    REPLACE(
                        REPLACE(
                            REPLACE(
                                REPLACE(
                                    CurrentGoalRevenues,
                                    '€',
                                    ''
                                ),
                                ',',
                                ''
                            ),
                            '"',
                            ''
                        ),
                        ' ',
                        ''
                    )
                ) AS CurrentSnapshotGoal


            FROM Project.ActionMonitoring_Import
        )


        --------------------------------------------------
        -- 5. INSERT SNAPSHOT
        --------------------------------------------------
        INSERT INTO Project.ActionMonitoringSnapshot
        (
            SnapshotDate,
            Subcategory,
            Country,
            PriorityType,
            SnapshotRevenue,
            PercCurrentSnapshotGoal,
            DeltaCurrentSnapshotGoal,
            CurrentSnapshotGoal
        )

        SELECT

            @SnapshotDate,
            Subcategory,
            Country,
            PriorityType,

            SnapshotRevenue,
            PercCurrentSnapshotGoal,
            DeltaCurrentSnapshotGoal,
			CurrentSnapshotGoal        


        FROM ImportPulito;


        --------------------------------------------------
        -- 6. CONTROLLO
        --------------------------------------------------
        SELECT
           

			  @SnapshotDate,
            Subcategory,
            Country,
            PriorityType,

            SnapshotRevenue,
            PercCurrentSnapshotGoal,
            DeltaCurrentSnapshotGoal,
			CurrentSnapshotGoal  

        FROM Project.ActionMonitoringSnapshot;


    END TRY

    BEGIN CATCH
        THROW;
    END CATCH

END;
